final restaurantMapList = [
  {
    "name": "Sahi Khana",
    "type": "Family Restaurant",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/images/bestfood/ic_best_food_7.jpeg",
    "description": "All kinds of Indian food is available.",
  },
  // {
  //   "name": "Burger King",
  //   "type": "Restaurant",
  //   "rating": 3.5,
  //   "goodReviews": 93.2,
  //   "totalScore": 72.2,
  //   "satisfaction": 89.2,
  //   "isfavourite": false,
  //   "image":"assets/images/restaurant.jpg",
  //   "description": "Burger , veggies, smoothies, ice creams are available at a cheap rate",
  // },
  // {
  //   "name": "Javed Habbib",
  //   "type": "Salon and Spa",
  //   "rating": 2.5,
  //   "goodReviews": 88.2,
  //   "totalScore": 93.94,
  //   "satisfaction": 78.2,
  //   "isfavourite": false,
  //   "image":"assets/images/spa.jpg",
  //   "description": "All kinds of haircut with different hairstyles, shaveing, spa, etc",
  // },
  // {
  //   "name": "Frank Ross",
  //   "type": "Pharmacy and Medical store",
  //   "rating": 1.5,
  //   "goodReviews": 12.2,
  //   "totalScore": 75.2,
  //   "satisfaction": 84.2,
  //   "isfavourite": true,
  //   "image":"assets/images/medicine.jpg",
  //   "description": "Medicines and other pharmacy products.",
  // },
];
